-- Fire Shield - Zone Action Seed Data
-- 17 actions from layer_80_20_steps.md, evidence-grounded and prioritized

-- LAYER 0: The House Itself (5 actions)
INSERT OR IGNORE INTO zone_actions VALUES
('layer0-vent-screening', 0, 'house', 1,
 'Screen all vents with 1/8-inch noncombustible metal mesh or install ember-resistant vents',
 'Attic vents, crawlspace vents, soffit vents, gable vents — every one is an ember highway into your home. Embers enter, ignite insulation or stored materials, and the house burns from the inside out with no exterior damage visible until it''s too late.',
 'This is the single highest-impact structural action. Embers don''t need the fire to reach your house — they travel miles ahead and enter through unprotected vents. Vent protection is one of four hardening features that together raised survival rates from 36% to 54% in the 2025 LA fires.',
 'IBHS Wildfire Prepared Home standard; CAL FIRE and NFPA guidance; IBHS 2025 LA Fire Investigation.',
 'low', '$15–50 per vent', '1–2 weekends',
 '["april","may","june","october","november"]', 0.98, 0),

('layer0-gutter-debris', 0, 'house', 2,
 'Clean all debris from roof, gutters, and downspouts — and keep them clean seasonally',
 'Dry leaves, pine needles, and moss in gutters are a primary ember ignition point. Burning gutter debris gets under the roof covering and ignites the underlayment. Even a metal roof fails if the gutter debris beneath its edge catches fire.',
 'IBHS research photos from the LA fires show gutter debris as a direct ignition pathway. CAL FIRE identifies this as the most common preventable ignition source. Zero cost — requires a ladder and 1–2 hours, repeated seasonally (critical before fire season: May/June in Southern Oregon).',
 'CAL FIRE Home Hardening guidance; IBHS post-fire documentation from 2025 LA fires.',
 'zero_cost', '$0', '1–2 hours, seasonal',
 '["april","may","june","september","october"]', 0.95, 0),

('layer0-gap-sealing', 0, 'house', 3,
 'Seal gaps around the garage door, windows, doors, and eaves with weatherstripping or noncombustible caulk',
 'Every gap is an ember entry point. Garage doors are especially vulnerable — embers blow under the door and ignite stored materials, vehicles, or the structure itself. Open or poorly sealed eaves trap embers and radiant heat.',
 'CAL FIRE Home Hardening guidance identifies garage door weatherstripping and gap sealing as priority actions. IBHS WPH standard requires it. A single burning doormat can ignite a front door through an unsealed gap.',
 'CAL FIRE Home Hardening guidance; IBHS Wildfire Prepared Home standard.',
 'low', '$10–30', '1–2 hours',
 '["march","april","may","october","november"]', 0.88, 0),

('layer0-evacuation-plan', 0, 'house', 4,
 'Have a written, practiced household evacuation plan',
 'Two evacuation routes. A documented meeting point. Who drives which vehicle with which people and pets. Where critical documents are stored. Who are your neighbors who may need help evacuating? The 2020 Almeda Fire (Phoenix/Talent, 5 miles from Ashland) showed what happens when people don''t have this — communication systems failed and many received no advance notification.',
 'The Almeda Fire destroyed 2,600+ homes in Talent and Phoenix. The Lahaina fire showed that even communities with plans failed when plans weren''t practiced. Camp Fire gave Paradise residents as little as 15 minutes to evacuate. Zero cost, one hour to create.',
 'Almeda Fire after-action reports; Ready, Set, Go! framework; Camp Fire evacuation analysis.',
 'zero_cost', '$0', '1 hour to create, review annually',
 '["march","june","september"]', 0.85, 0),

('layer0-go-bag', 0, 'house', 5,
 'Prepare a go-bag that is ready to grab in under 5 minutes',
 'Medications, documents (or copies), phone chargers, cash, change of clothes, pet supplies, water. Stored by the door you''d exit through. If you have to think about what to grab, you''ve already lost critical evacuation time.',
 'Every fire agency recommends this. The Camp Fire gave Paradise residents as little as 15 minutes. The Almeda Fire moved through Talent and Phoenix in hours. You already own the items — one hour to assemble, stored permanently by your exit door.',
 'Camp Fire evacuation documentation; FEMA Ready.gov; Ready, Set, Go! framework.',
 'zero_cost', '$0', '1 hour to assemble',
 '["may","june","july","august","september"]', 0.82, 0),

-- LAYER 1: 0 to 5 Feet (5 actions)
('layer1-under-deck-debris', 1, '0_5ft', 1,
 'Clear ALL debris from under decks, porches, stairs, and raised structures',
 'Dead leaves, pine needles, cobwebs, stored items, firewood — everything under the deck. IBHS research shows deck ignition typically occurs from ember accumulation in gaps between deck boards at joist crossings, where debris collects underneath. Embers fall through the gaps, land on the debris pile, and ignite the underside of the deck. The deck then ignites the house.',
 'Your property could look perfect from the street and fail from a single pile of leaves under the back deck. A Jackson County fire inspector recently flagged exactly this — a well-maintained property with dangerous hidden debris under the deck. Zero cost, 30 minutes, repeat monthly during leaf drop and before fire season.',
 'IBHS deck vulnerability research; IBHS post-fire photos from 2025 LA fires; Berkeley FireSafe research.',
 'zero_cost', '$0', '30 minutes, monthly during fire season',
 '["april","may","june","july","august","september","october"]', 0.97, 0),

('layer1-remove-combustibles', 1, '0_5ft', 2,
 'Remove all combustible materials from the 0–5 foot perimeter',
 'No bark mulch. No firewood stacks. No propane tanks. No wooden patio furniture. No wicker baskets. No doormats (especially coir/natural fiber). No dried flower arrangements. No newspapers or recycling bins. During fire weather events, move combustible items indoors.',
 'IBHS WPH standard prohibits combustible materials in Zone Zero. IBHS post-fire documentation shows combustible items (hot tubs, furniture, planters) igniting and spreading fire to structures. Berkeley FireSafe research found clearing the first five feet is the single most important exterior step to prevent ignition.',
 'IBHS Wildfire Prepared Home standard; Berkeley FireSafe research; NFPA Firewise Zone Zero requirements.',
 'zero_cost', '$0 for removal', '1–2 hours',
 '["may","june","july","august","september"]', 0.94, 0),

('layer1-replace-mulch', 1, '0_5ft', 3,
 'Replace organic mulch and ground cover with gravel, rock, decorative stone, or concrete within 5 feet',
 'IBHS testing demonstrated fire spreading through combustible wood mulch and stopping when it reached noncombustible rock landscaping, preventing flames from reaching the home. Bark mulch within 5 feet of the house is a fuse — it connects ember landing to the structure.',
 'IBHS research center testing videos show this clearly. NFPA Firewise Zone Zero requirements. CAL FIRE defensible space guidance. Moderate one-time cost with permanent benefit.',
 'IBHS research center testing; NFPA Firewise Zone Zero requirements; CAL FIRE defensible space guidance.',
 'moderate', '$100–400 depending on area', 'Half-day project',
 '["march","april","october","november"]', 0.88, 0),

('layer1-noncombustible-fence', 1, '0_5ft', 4,
 'Use noncombustible material for fencing, gates, and trellises where they attach to the house',
 'A burning wooden fence acts as a direct fire pathway to your exterior wall. IBHS recommends noncombustible fencing within 5 feet of the structure, including where gates attach to the house. Metal, stone, or masonry for at least the first fence section closest to the structure.',
 'IBHS post-fire documentation shows combustible fence sections attached to homes as a direct ignition pathway. WPH standard requires noncombustible fencing within 5 feet. Can be done in stages — replace just the section nearest the house first.',
 'IBHS post-fire documentation; IBHS Wildfire Prepared Home standard.',
 'moderate', 'Varies by fence length', '1 day project',
 '["march","april","october","november"]', 0.82, 0),

('layer1-enclose-deck', 1, '0_5ft', 5,
 'Enclose the underside of raised decks with 1/8-inch metal mesh or noncombustible skirting',
 'If the deck is elevated, the open underside is an ember trap. Enclosing it with mesh blocks ember entry while allowing airflow. Do not use wooden lattice — it burns. Even with the underside enclosed, keep the area clear of debris.',
 'University of Nevada Extension guidance. IBHS deck research shows elevated decks with open undersides are among the most vulnerable structural features. CAL FIRE Ready for Wildfire deck guidance. Do not use wooden lattice — it is a combustible ember receptor, not a barrier.',
 'University of Nevada Extension; IBHS deck research; CAL FIRE Ready for Wildfire.',
 'moderate', '$50–200', 'Half-day project',
 '["march","april","october","november"]', 0.78, 0),

-- LAYER 2: 5 to 30 Feet (3 actions)
('layer2-ladder-fuels', 2, '5_30ft', 1,
 'Eliminate ladder fuels — prune tree branches up to 6–10 feet from ground, remove shrubs growing under trees',
 'Prune tree branches up to 6–10 feet from the ground. Remove shrubs, brush, and tall grass growing directly under trees. Remove any vegetation "staircase" that connects ground cover → shrubs → tree canopy → roof. This single action breaks the vertical fire pathway.',
 'Every fire science source identifies ladder fuels as the primary mechanism that turns a ground fire into a structure-threatening crown fire. Syphard et al. found the most effective defensible space treatment was in the 5–20 meter range. If fire can''t climb from the ground into the canopy, it stays manageable.',
 'Syphard et al. 2019 statewide California analysis; NFPA Firewise intermediate zone guidance; NIFC defensible space research.',
 'low', 'Hand tools only', 'Several hours for typical lot',
 '["march","april","october","november","december","january","february"]', 0.85, 1),

('layer2-canopy-spacing', 2, '5_30ft', 2,
 'Create horizontal spacing between plants and tree canopies — at least 10 feet between canopies',
 'Trees should have at least 10 feet between canopies in this zone. Shrubs should be in small, isolated clusters, not continuous hedgerows. The goal is to break horizontal fuel continuity so fire can''t race across a connected carpet of vegetation toward the house.',
 'NFPA Firewise intermediate zone guidance. Spacing requirements increase on slopes — steeper slope requires more spacing. Continuous vegetation hedgerows act as a fuse from the wildland toward the structure. Breaking that continuity forces fire to slow and drop to the ground.',
 'NFPA Firewise zone guidance; CAL FIRE defensible space slope tables.',
 'low', 'Labor only if removing; moderate if replanting', 'Half-day',
 '["march","april","october","november"]', 0.78, 1),

('layer2-dead-vegetation', 2, '5_30ft', 3,
 'Remove all dead vegetation, dry leaf litter, and dead branches in the 5–30 foot zone',
 'Dead plants are the driest, most ignitable material in your yard. A single dead shrub within 30 feet of the house is a high-priority ember receptor. Regularly clear fallen leaves, pine needles, and dead branches from this zone — especially before and during fire season.',
 'NIFC and NFPA defensible space guidance. CAL FIRE identifies dead vegetation removal as a top-priority seasonal action. Dead material ignites at a much lower temperature and burns more intensely than live, hydrated vegetation. This is a zero-cost ongoing action.',
 'NIFC defensible space guidance; NFPA Firewise zone requirements; CAL FIRE seasonal guidance.',
 'zero_cost', '$0', '1–3 hours seasonally',
 '["april","may","june","july","august","september"]', 0.72, 0),

-- LAYER 3: 30 to 100 Feet (2 actions)
('layer3-thin-trees', 3, '30_100ft', 1,
 'Thin trees to reduce canopy density and remove dead or dying vegetation',
 'Remove smaller conifers growing between mature trees. Reduce overall tree density so canopies don''t form a continuous overhead fuel layer. Remove all dead standing trees (snags) and dead material. On slopes, spacing must increase — fire moves faster uphill, so fuel breaks need to be wider.',
 'NFPA extended zone guidance. USFS defensible space research. Slope-adjusted spacing tables from CAL FIRE. This zone transitions fire behavior — if fuel here is discontinuous and low, flames stay small and on the ground by the time they reach your inner zones.',
 'NFPA Firewise extended zone guidance; CAL FIRE slope-adjusted spacing; USFS defensible space research.',
 'high', 'May require professional forestry work for larger properties', '1–2 days for typical lot',
 '["november","december","january","february","march"]', 0.65, 1),

('layer3-outbuildings', 3, '30_100ft', 2,
 'Clear vegetation and combustible storage around all outbuildings, sheds, propane tanks, and structures in this zone',
 'An unmitigated shed at 80 feet becomes a secondary ignition source. If it catches fire, it produces enough radiant heat and embers to threaten the house as if the wildfire were at close range. Apply Zone 1 principles (noncombustible perimeter, debris clearing) around any structure in this zone.',
 'IBHS post-fire documentation shows outbuilding ignition as a common pathway to primary structure loss. NFPA guidance explicitly covers accessory structures. Propane tanks are especially critical — they can explode and throw burning debris.',
 'IBHS post-fire documentation; NFPA Firewise guidance on accessory structures.',
 'low', 'Low to moderate cost', 'Half-day project per outbuilding',
 '["april","may","june","september","october"]', 0.68, 0),

-- LAYER 4: 100+ Feet (2 actions)
('layer4-driveway-access', 4, '100ft_plus', 1,
 'Ensure driveway and access road are passable for fire engines (12-foot width, 13.5-foot clearance, turnaround)',
 '12-foot minimum width. 13.5-foot vertical clearance (trim overhanging branches). Turnaround space or pullout for large apparatus. If firefighters can''t safely reach your property, they will bypass it. Properties that are inaccessible are triaged out during active fire events.',
 'NFPA access requirements. Fire department operational standards. Most relevant for rural Applegate Valley, Jacksonville foothills, and Ashland hillside properties. This is binary — either firefighters can reach you or they can''t. Inaccessible properties are skipped.',
 'NFPA Firewise access requirements; fire department operational standards.',
 'low', 'Trimming only; potentially moderate if road widening needed', 'Half-day',
 '["march","april","may"]', 0.60, 0),

('layer4-address-signage', 4, '100ft_plus', 2,
 'Install reflective address signage visible in smoke and at night, and clear vegetation along the driveway corridor',
 'Firefighters need to find you fast in zero-visibility conditions. A reflective, noncombustible address sign at the road and at any driveway forks is the difference between getting help and being bypassed. Clear vegetation 10 feet on each side of the driveway so it doesn''t become a fire corridor.',
 'Post-fire reports consistently cite inability to locate properties as a factor in protection decisions. Very low cost ($10–30 for signage) with potentially life-saving impact. Clear the driveway corridor to prevent it from acting as a flame channel toward the structure.',
 'Fire department access guidelines; post-fire reports on property location failures.',
 'low', '$10–30 for signage', '2–3 hours',
 '["march","april","may"]', 0.58, 0);
